PLUGIN_NAME=			adguardhome-guru
PLUGIN_VERSION=		1.3
PLUGIN_REVISION=  2
PLUGIN_COMMENT=		AdGuardHome DNS plugin for OPNsense 24.7,v25.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
