PLUGIN_NAME=			adguardhome
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=  5
PLUGIN_COMMENT=		AdGuardHome DNS plugin for OPNsense 24.7
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
