PLUGIN_NAME=			nextdns
PLUGIN_VERSION=		1.44.3
PLUGIN_REVISION=  0.1
PLUGIN_COMMENT=		NextDNS DNS plugin for OPNsense 24.7, 25.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
