#!/bin/sh

# 2024-11-03

# PROVIDE: adguardhome
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown
#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# adguardhome_enable (bool):	Set to NO by default.
#			Set it to YES to enable adguardhome.
# ADGUARDHOME_CONFIG (str):	Set to /usr/local/etc/adguardhome/adguardhome.yaml by default.
#			Set it to a path to use that config file.
# ADGUARDHOME_CONFIG_SAMPLE: Set to /usr/local/etc/adguardhome/adguardhome.yaml.sample by default
#			Set it to a path to use sample config file.
# ADGUARDHOME_USER (str):	Services run as root by default. Set to a user name
#			to run adguardhome as that user. Note: non-root users
#			might need permission to bind to ports.
# ADGUARDHOME_GROUP (str):	Set to the user's primary group by default.
#			Set it to a group name for daemon file ownership.
# ADGUARDHOME_FLAGS (str):	Enter extra flags to append to the adguardhome command.
#!/bin/sh

. /etc/rc.subr

name=AdGuardHome
## DO NOT CHANGE THE ABOVE VARIABLE, to be always called name

rcvar=adguardhome_enable

load_rc_config ${name}

: ${adguardhome_enable:=NO}
: ${ADGUARDHOME_CONFIG:="/usr/local/etc/adguardhome/adguardhome.yaml"}
: ${ADGUARDHOME_GROUP:=}
: ${ADGUARDHOME_FLAGS:="-s run"}
: ${ADGUARDHOME_CONFIG_SAMPLE:="/usr/local/etc/adguardhome/adguardhome.yaml.sample"}

ADGUARDHOME_LOGFILE="/var/log/${name}/${name}.log"
ADGUARDHOME_PIDFILE="/var/run/${name}.pid"
ADGUARDHOME_PATH="/usr/local/bin/${name}"

if [ -n "${ADGUARDHOME_USER}" ] && [ -z "${ADGUARDHOME_GROUP}" ]; then
	# Detect the daemon user's primary group
	ADGUARDHOME_GROUP=$(id -gn "${ADGUARDHOME_USER}")
fi

command="/usr/sbin/daemon"
procname=${ADGUARDHOME_PATH}
command_args="-c -f -o ${ADGUARDHOME_LOGFILE} -p ${ADGUARDHOME_PIDFILE} ${ADGUARDHOME_PATH} -c ${ADGUARDHOME_CONFIG} ${ADGUARDHOME_FLAGS} &"

#/usr/sbin/daemon -c -f -o /var/log/adguardhome/adguardhome.log -p /var/run/adguardhome.pid /root/temp/adguardhome run -config-file /usr/local/etc/adguardhome/adguardhome.conf &

start_precmd="adguardhome_precmd"
# Sets up a ADGUARDHOME_PIDFILE the daemon user can access
adguardhome_precmd()
{
	install -o "${ADGUARDHOME_USER:-root}" -g "${ADGUARDHOME_GROUP:-wheel}" -m 0600 /dev/null "${ADGUARDHOME_PIDFILE}"
}


status_cmd=adguardhome_status
adguardhome_status()
{
	if [ -n "$rc_pid" ]; then
		echo "${name} is running as pid $rc_pid (through OPNsense os-adguardhome plugin)."
		return 0
	else
		echo "${name} is not running."
  fi
}

#stop_cmd="killall adguardhome"
stop_cmd=adguardhome_stop
#stop_cmd=adguardhome_stop_asservice

adguardhome_stop()
{
	# wait for process to exit
	if [ -n "$rc_pid" ]; then
		echo "Stopping ${name} (through OPNsense os-adguardhome plugin)."
		kill $rc_pid
		echo "Waiting for PIDS: $rc_pid  (through OPNsense os-adguardhome plugin)."
		wait_for_pids $rc_pid
		echo " Stopped ${name} (through OPNsense os-adguardhome plugin)."
	else
		echo "${name} is not running (through OPNsense os-adguardhome plugin)."
	fi
}


# Create adguardhome-config from sample, else do not overwrite existing
if [ -f "${ADGUARDHOME_CONFIG}" ]; then
  # If adguardhome config file exists, then do not overwrite; do nothing !
 else
  # If no adguardhome config file found; assume a new install; copy sample as config file 
  cp "${ADGUARDHOME_CONFIG_SAMPLE}" "${ADGUARDHOME_CONFIG}";
fi

# Create adguardhome logfile directory and file
if [ -f "${ADGUARDHOME_LOGFILE}" ]; then
  # If adguardhome log file exists, then do not overwrite; do nothing !
 else
  # If no adguardhome log file found; assume a new install; create log directory 
  mkdir -p /var/log/${name}/
  touch "${ADGUARDHOME_LOGFILE}"
fi

run_rc_command "$1"
